### ISSUE TITLE
Include steps to build/run locally

### ISSUE THREAD

**Issue by rohit-gohri** [karthiks3000/postman-doc-gen#1]
The executable in the releases is a unix executable and is not runnable everywhere.
Include requirements and steps so that we can build the project locally.

**Comment by karthiks3000** [comment]
Are you trying to run it on a windows? I'll update the readme in sometime, but to build it locally -

- clone the repo
- pip install the dependencies in the requirements.txt file (with or without a virtualenv)
- and run the code using the command: python postman_doc_gen.py [collection.json]

You will need python 3 to run the code

**Comment by rohit-gohri** [comment]
Thanks, will try

**Comment by hitswa** [comment]
Tried to follow what you mentioned. Following is the result.

`> python postman_doc_gen.py collection.json -o ./ `

```
Traceback (most recent call last):
  File "postman_doc_gen.py", line 30, in <module>
    d.generate_doc(args.collection, args.env, args.out)
  File "C:\...\postman-doc-gen-0.1.0\postman_doc_gen\document_g
enerator.py", line 42, in generate_doc
    self.add_items(self.side_tree, json_collection)
  File "C:\...\postman-doc-gen-0.1.0\postman_doc_gen\document_g
enerator.py", line 134, in add_items
    self.add_apis(item)
  File "C:\...\postman-doc-gen-0.1.0\postman_doc_gen\document_g
enerator.py", line 151, in add_apis
    api.examples = self.get_examples(api, item.get(constants.RESPONSE, []))
  File "C:\...\postman-doc-gen-0.1.0\postman_doc_gen\document_g
enerator.py", line 171, in get_examples
    api_example.request_body = api_example.request_body + '\n' + res.get(constan
ts.ORIGINAL_REQUEST).get(
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by karthiks3000** [comment]
I'll take a look at this. This is un-related to the original issue and should ideally have been created as a separate issue.

**Comment by karthiks3000** [comment]
@hitswa I just pushed out a new release, can you confirm if the bug is resolved for you?
https://github.com/karthiks3000/postman-doc-gen/releases/tag/v1.0.1
