### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 56057: character maps to <undefined>

### ISSUE THREAD

**Issue by igormorse** [karthiks3000/postman-doc-gen#17]
I getting this error when trying to generate from my collection. Probably due special characters like ~, ç, ´, ` and others that are present in my language.

**Comment by karthiks3000** [comment]
I dont think those special characters are supported right now. I'll see if I can find a library that handles them, but I dont think I'll get time to look into it anytime soon.
