### ISSUE TITLE
How do I get this tool to work under Linux/Deb9

### ISSUE THREAD

**Issue by gromran** [karthiks3000/postman-doc-gen#20]
get this error:
>python3 postman_doc_gen.py "/home/postman/API.collection.json" -e "/home/postman/v5.environment.json" -o >/tmp/docuhtml/
>  File "postman_doc_gen.py", line 14
>    version=f"{parser.prog} Version 1.2.0"
>                                         ^
>SyntaxError: invalid syntax

same with python(2).

I don't have much to do with python and have tried the install steps, but I also get a lot of errors in the requirements.txt
- No matching distribution found for importlib-metadata
- No matching distribution found for jinja-markdown

the executable does'nt work too:
> -bash: ./postman_doc_gen: Unable to execute the binary: Error in the format of the program file

The Win exe works but that doesn't help me because our Jenkins runs on Linux.

**Comment by karthiks3000** [comment]
Try running the command by passing in the location without quotes. 

postman_doc_gen /home/postman/API.collection.json -e /home/postman/v5.environment.json -o /tmp/docuhtml/

if that doesn't work, it may have something to do with the collection itself. I tried the latest version on my macos and it worked for me (using a new postman v2 export).

**Comment by gromran** [comment]
I got it to work after I fiddled around with the Python versions for a long time yesterday.
