### ISSUE TITLE
It didn't parse XML response on response.

### ISSUE THREAD

**Issue by anson338** [karthiks3000/postman-doc-gen#6]

**Comment by karthiks3000** [comment]
@anson338  can you provide an example?

**Comment by anson338** [comment]
[test.zip](https://github.com/karthiks3000/postman-doc-gen/files/5192573/test.zip)
Sure.

**Comment by anson338** [comment]
@karthiks3000 any updates? ;D

**Comment by karthiks3000** [comment]
@anson338 this should be resolved in the latest release 
https://github.com/karthiks3000/postman-doc-gen/releases/tag/1.1.1
