### ISSUE TITLE
Postman Environment Support

### ISSUE THREAD

**Issue by rajib-raiyat** [karthiks3000/postman-doc-gen#7]
Can you please make a environment support for your software ? 
```sh
python postman_doc_gen.py [path/to/collection] -o [path/to/output/folder] -i [path/to/postman_enviroment]
```

**Comment by karthiks3000** [comment]
@rajib-raiyat  can you be more specific? The tool supports applying environments already

**Comment by rajib-raiyat** [comment]
@karthiks3000 Thanks for your support.

I have postman collections and in this collection I have some variables, suppose one of them {{base_url}}. So when I want to make a documentation there is no option(as far as I know) to set my postman environment with the collection in `postman-doc-gen`.

So as a result, I got the URL in documentation which looks like `{{base_url}}/api/user`. But If I can provide the environment then the URL will look like `example.com/api/user`

**Comment by karthiks3000** [comment]
So the tool does support environment variables, but they are applied to the examples associated with each request. 

To apply environment values to the examples, use the following command -

./postman_doc_gen [path/to/collection] -o [path/to/output/folder] -e [path/to/environment/json]

**Comment by rajib-raiyat** [comment]
OK thanks. But what if I want to use  [Build localy](https://github.com/karthiks3000/postman-doc-gen#to-build-locally) ? Or how to use this software in linux ?

**Comment by karthiks3000** [comment]
The readme has the steps to build locally.

**Comment by rajib-raiyat** [comment]
Yes, I know how to build locally. But I want to use environment in build locally method. Which you describe in [this comment](https://github.com/karthiks3000/postman-doc-gen/issues/7#issuecomment-768349465).

**Comment by karthiks3000** [comment]
You just modify the build locally command as per the above example

`python postman_doc_gen [path/to/collection] -o [path/to/output/folder] -e [path/to/environment/json]`
